services:
  - type: web
    name: phstatic3
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
